package com.beetloop.vendorproducts.pm.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.index.Indexed;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * An issue or escalation — BRD §6.8 (PM-10), ID series ISS / ESC.
 *
 * <p>Issues are listed by assignee and are visible to the concerned user. Per
 * §12.2 the auto-generated Project Manager escalations (§11.4) use the ESC
 * series but land in the same list, so {@link #kind} distinguishes them.
 */
public class PmIssue {

    @Id
    private UUID id;

    /** Business ID from the BRD §12.2 matrix. */
    @Indexed(unique = true)
    private String code;

    @Transient
    private PmProject project;

    private int position;

    private String orderCode;

    /** ISS raised by a user; ESC auto-generated by the PM. */
    private PmEnums.IssueKind kind;

    private String title;

    private String description;

    private PmEnums.IssueSeverity severity;

    private PmEnums.IssueStatus status;

    private PmEnums.PmParty raisedBy;

    private String raisedByName;

    /** PM-10 — in the vendor context, assignable to buyer or vendor. */
    private PmEnums.PmParty assignedTo;

    private String assignedToName;

    private java.time.LocalDate dueDate;

    private Instant resolvedAt;

    private String resolution;

    private Instant createdAt;

    private Instant updatedAt;

    void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public PmProject getProject() {
        return project;
    }

    public void setProject(PmProject project) {
        this.project = project;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public String getOrderCode() {
        return orderCode;
    }

    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    public PmEnums.IssueKind getKind() {
        return kind;
    }

    public void setKind(PmEnums.IssueKind kind) {
        this.kind = kind;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public PmEnums.IssueSeverity getSeverity() {
        return severity;
    }

    public void setSeverity(PmEnums.IssueSeverity severity) {
        this.severity = severity;
    }

    public PmEnums.IssueStatus getStatus() {
        return status;
    }

    public void setStatus(PmEnums.IssueStatus status) {
        this.status = status;
    }

    public PmEnums.PmParty getRaisedBy() {
        return raisedBy;
    }

    public void setRaisedBy(PmEnums.PmParty raisedBy) {
        this.raisedBy = raisedBy;
    }

    public String getRaisedByName() {
        return raisedByName;
    }

    public void setRaisedByName(String raisedByName) {
        this.raisedByName = raisedByName;
    }

    public PmEnums.PmParty getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(PmEnums.PmParty assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getAssignedToName() {
        return assignedToName;
    }

    public void setAssignedToName(String assignedToName) {
        this.assignedToName = assignedToName;
    }

    public java.time.LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(java.time.LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public Instant getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(Instant resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public String getResolution() {
        return resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
