package com.beetloop.vendorproducts.pm.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * An issue or escalation — BRD §6.8 (PM-10), ID series ISS / ESC.
 *
 * <p>Issues are listed by assignee and are visible to the concerned user. Per
 * §12.2 the auto-generated Project Manager escalations (§11.4) use the ESC
 * series but land in the same list, so {@link #kind} distinguishes them.
 */
@Entity
@Table(name = "pm_issue", indexes = {@Index(name = "idx_pm_issue_code", columnList = "code"), @Index(name = "idx_pm_issue_parent", columnList = "project_id")})
public class PmIssue {

    @Id
    @GeneratedValue
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Business ID from the BRD §12.2 matrix. */
    @Column(name = "code", length = 40, nullable = false, unique = true)
    private String code;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "project_id", nullable = false)
    private PmProject project;

    @Column(name = "position", nullable = false)
    private int position;

    @Column(name = "order_code", length = 40)
    private String orderCode;

    /** ISS raised by a user; ESC auto-generated by the PM. */
    @Enumerated(EnumType.STRING)
    @Column(name = "kind", length = 30, nullable = false)
    private PmEnums.IssueKind kind;

    @Column(name = "title", length = 400, nullable = false)
    private String title;

    @Column(name = "description", length = 4000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", length = 20, nullable = false)
    private PmEnums.IssueSeverity severity;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private PmEnums.IssueStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "raised_by", length = 30, nullable = false)
    private PmEnums.PmParty raisedBy;

    @Column(name = "raised_by_name", length = 200)
    private String raisedByName;

    /** PM-10 — in the vendor context, assignable to buyer or vendor. */
    @Enumerated(EnumType.STRING)
    @Column(name = "assigned_to", length = 30)
    private PmEnums.PmParty assignedTo;

    @Column(name = "assigned_to_name", length = 200)
    private String assignedToName;

    @Column(name = "due_date")
    private java.time.LocalDate dueDate;

    @Column(name = "resolved_at")
    private Instant resolvedAt;

    @Column(name = "resolution", length = 4000)
    private String resolution;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public PmProject getProject() {
        return project;
    }

    public void setProject(PmProject project) {
        this.project = project;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public String getOrderCode() {
        return orderCode;
    }

    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    public PmEnums.IssueKind getKind() {
        return kind;
    }

    public void setKind(PmEnums.IssueKind kind) {
        this.kind = kind;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public PmEnums.IssueSeverity getSeverity() {
        return severity;
    }

    public void setSeverity(PmEnums.IssueSeverity severity) {
        this.severity = severity;
    }

    public PmEnums.IssueStatus getStatus() {
        return status;
    }

    public void setStatus(PmEnums.IssueStatus status) {
        this.status = status;
    }

    public PmEnums.PmParty getRaisedBy() {
        return raisedBy;
    }

    public void setRaisedBy(PmEnums.PmParty raisedBy) {
        this.raisedBy = raisedBy;
    }

    public String getRaisedByName() {
        return raisedByName;
    }

    public void setRaisedByName(String raisedByName) {
        this.raisedByName = raisedByName;
    }

    public PmEnums.PmParty getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(PmEnums.PmParty assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getAssignedToName() {
        return assignedToName;
    }

    public void setAssignedToName(String assignedToName) {
        this.assignedToName = assignedToName;
    }

    public java.time.LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(java.time.LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public Instant getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(Instant resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public String getResolution() {
        return resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
